1. NumPy kütüphanesi np kısaltması ile import edin

In [1]:
import numpy as np

2. 10 tane 0 değerinden oluşan bir array oluşturun

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. 10 tane 1 değerinden oluşan bir array oluşturun

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

4. 10 tane 5 değerinden oluşan bir array oluşturun

In [8]:
arr = np.ones(10) * 5
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

5. 10'dan 50'ye kadar(10 ve 50 dahil) ardışık tam sayılardan oluşan bir array oluşturalım

In [10]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

6. 10 ve 50 arasındaki çift tam sayılardan oluşan bir array oluşturalım. (10 ve 50 dahil)

In [12]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

7. 3x3 shape'inde 0'dan 8'e kadar toplam 9 tam sayıdan oluşan bir array oluşturalım

In [19]:
arr = np.arange(9).reshape((3,3))
arr


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

9. NumPy kullanarak 0-1 arasından rastgele bir sayı oluşturun.

In [23]:
np.random.rand(1)

array([0.28656109])

10. NumPy kullanarak standart dağılıma sahip 25 random sayıdan oluşan bir array oluşturalım.

In [24]:
np.random.rand(25)

array([0.41127403, 0.86862305, 0.08923348, 0.2598918 , 0.74827534,
       0.28087431, 0.76814957, 0.89491427, 0.55416097, 0.14749017,
       0.37605914, 0.09808871, 0.5480618 , 0.12357263, 0.46486391,
       0.62760896, 0.43621783, 0.45895741, 0.75753166, 0.76352242,
       0.69949821, 0.47646208, 0.31122642, 0.95947936, 0.91981769])

11. Aşağıdaki çıktıdakine benzer array'i oluşturmaya çalışın

In [25]:
arr = np.linspace(0.01, 1.0, num=100).reshape(10, 10)
arr = np.round(arr, decimals=2)
print(arr)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


12. 0-1 arasında lineer artış gösteren ve 20 sayıdan oluşan bir array oluşturun:

In [30]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# NumPy Indexing and Selection

In [31]:
# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

13. Aşağıda verilen matrisleri oluşturmaya çalışın.

In [49]:
arr = np.array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
arr


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

14. Write code that reproduces the output shown below.

In [51]:
arr[1][3]

20

15. mat arrayini kullanarak aşağıdaki matris çıktısını verecek kodları oluşturun

In [52]:
arr = np.array([[ 2],
       [ 7],
       [12]])
arr

array([[ 2],
       [ 7],
       [12]])

16. mat arrayini kullanarak aşağıdaki matris çıktısını verecek kodları oluşturun

In [55]:
arr = np.array([21, 22, 23, 24, 25])
arr

array([21, 22, 23, 24, 25])

17. mat arrayini kullanarak aşağıdaki matris çıktısını verecek kodları oluşturun

In [56]:
arr = np.array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
arr

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# NumPy Operations

18. Mat arrayindeki bütün değerlerin toplamını bulun

In [60]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [61]:
mat.sum()

325

19. Mat arrayindeki değerlerin standart sapmasını bulun

In [62]:
mat.std()

7.211102550927978

20. Mat arrayindeki her sütunun kendi içinde toplamlarını bularak yeni bir array oluşturun

In [63]:
arr = np.sum(mat, axis=0)
arr

array([55, 60, 65, 70, 75])