In [ ]:
import numpy as np

1) Manuel değerleri el ile girerek 3 boyutlu bir array oluşturup bir değişkene atayın. Ardından 3 boyutlu olup olmadığına bakmak için dimension'ını kontrol edin

In [6]:
arr3d = np.array([[[1,2,3] , [4,5,6]] , [[7,8,9] , [10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [47]:
arr3d.ndim

3

2) 34, 40, 46, 52... 112 şeklinde devam eden 1 boyutlu bir array oluşturun.

In [11]:
np.arange(34,113,6)

array([ 34,  40,  46,  52,  58,  64,  70,  76,  82,  88,  94, 100, 106,
       112])

3) 50-500 arasında lineer artış gösteren 91 tane tam sayıdan oluşan bir array oluşturun.(dtype'ı int olsun)

In [13]:
np.linspace(50,500,91, dtype = int)

array([ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95, 100, 105, 110,
       115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175,
       180, 185, 190, 195, 200, 205, 210, 215, 220, 225, 230, 235, 240,
       245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300, 305,
       310, 315, 320, 325, 330, 335, 340, 345, 350, 355, 360, 365, 370,
       375, 380, 385, 390, 395, 400, 405, 410, 415, 420, 425, 430, 435,
       440, 445, 450, 455, 460, 465, 470, 475, 480, 485, 490, 495, 500])

4) 100(10 ** 2) ile 10000(10 ** 5) arasında logaritmik artış gösteren 8 sayıdan oluşan bir array oluşturun.

In [14]:
np.logspace(2,5,8)

array([   100.        ,    268.26957953,    719.685673  ,   1930.69772888,
         5179.47467923,  13894.95494373,  37275.93720315, 100000.        ])

5) 0-8 tam arasındaki ardışık tam sayılardan oluşan(0 ve 8 dahil toplam 9 değer) 3x3 shape'inde bir matris oluşturun.

In [21]:
matrix = [[0, 1, 2],
          [3, 4, 5],
          [6, 7, 8]]


6) 6x6 formatında bir sıfır matrisi oluşturun. (dtype'ı int olsun)

In [24]:
np.zeros((6,6),dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

7) 4x4 formatında bir bir matrisi oluşturun. (dtype'ı int olsun)

In [25]:
np.ones((4,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

8) 8x8 formatında bir birim matris oluşturun. (Sadece sol köşegeni 1 geri kalan değerleri 0 olan matris'e birim matris deniyor.) (dtype'ı int olsun)

In [29]:
np.eye(8 , dtype = 'int')

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

9) 5x5 formatında bir köşegen matrisi oluşturun (Sadece sol üstten sağ alta doğru olan köşegendeki değerleri 3 olsun diğer bütün değerleri 0) (Bunu henüz görmediniz ama birim matrise benziyor, sadece köşegen değerleri 1 değil 3 olacak. Bir şeyler düşünün)

In [34]:
matrix = np.zeros((5, 5), dtype=int)
for i in range(5):
    matrix[i][i] = 3

print(matrix)

[[3 0 0 0 0]
 [0 3 0 0 0]
 [0 0 3 0 0]
 [0 0 0 3 0]
 [0 0 0 0 3]]


10) np.random modülünden uygun fonksiyonu kullanarak 0-1 arasında toplam 6 tane değerden oluşan 1 boyutlu bir array oluşturun.

In [35]:
np.random.rand(6)

array([0.19691835, 0.26581346, 0.26923898, 0.38903306, 0.76014337,
       0.38768648])

11) np.random modülünden uygun fonksiyonu kullanarak 50-100 arasındaki(50 ve 100 dahil) tam sayılardan 10 tanesiyle oluşan (5,2) shape'inde bir array oluşturun. Ardından bu arrayin shape'ini kontrol edin.

In [43]:
arrd = np.random.randint(50,101 , (5,2))
arrd

array([[78, 70],
       [76, 97],
       [65, 80],
       [80, 69],
       [85, 85]])

In [44]:
arrd.shape

(5, 2)

12) np.random modülünden uygun fonksiyonu kullanarak 100-1000(1000 dahil değil) arasındaki tam sayılardan rastgele 50 tanesinden oluşan (2,5,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in dimension'ını(boyutunu) ve shape'ini kontrol edin.

In [45]:
arr3d = np.random.randint(100,1000, (2,5,5))
arr3d

array([[[744, 732, 848, 343, 934],
        [640, 718, 317, 417, 257],
        [842, 790, 480, 242, 374],
        [141, 420, 216, 707, 719],
        [580, 251, 100, 540, 426]],

       [[991, 235, 757, 693, 905],
        [927, 806, 589, 502, 300],
        [816, 838, 490, 971, 450],
        [994, 224, 877, 905, 261],
        [863, 215, 982, 387, 282]]])

In [46]:
arr3d.shape

(2, 5, 5)

In [48]:
arr3d.ndim

3

13) np.random modülünden uygun fonksiyonu kullanarak 0-100(0 ve 100 dahil) arasındaki tam sayılardan 10 tane seçerek bir array oluşturun. Bu array'in maximum, mininmum değerlerine ve bu değerlerin indexlerine bakın.

In [50]:
arr = np.random.randint(0,101,10)
arr

array([72,  6, 55, 91, 43, 57, 97, 72, 89, 82])

In [51]:
arr.max()

97

In [52]:
arr.argmax()

6

In [53]:
arr.min()

6

In [55]:
arr.argmin()

1

14) np.random modülünden uygun fonksiyonu kullanarak 300-500(300 ve 500 dahil) arasındaki tam sayılardan 20 tane seçerek (2,2,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in içindeki 20 tam sayı arasından maximum ve minimum değerleri manuel olarak tespit edin ve indexleme yaparak çekmeye çalışın.

In [59]:
arr = np.random.randint(300,500,20)
arr

array([423, 485, 442, 376, 372, 306, 493, 319, 404, 424, 424, 348, 446,
       403, 361, 323, 381, 424, 378, 322])

In [62]:
arr3d = arr.reshape(2,2,5)
arr3d

array([[[423, 485, 442, 376, 372],
        [306, 493, 319, 404, 424]],

       [[424, 348, 446, 403, 361],
        [323, 381, 424, 378, 322]]])

In [63]:
arr3d.max()

493

In [64]:
arr3d.argmax()

6

In [65]:
arr3d.min()

306

In [66]:
arr3d.argmin()

5

15) 0-50(50 dahil) arasındaki ardışık tam sayılardan oluşan bir array oluşturun. Ardından bu arrayin 20. ve 35. indexleri arasındaki değerleri 500'e eşitleyin ve yeni oluşan array'i ekrana yazdırarak broadcasting işleminin yapılıp yapılmadığını test edin.

In [71]:
arr = np.arange(0,51)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [72]:
arr[20:35] = 500
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 500, 500, 500, 500, 500,
       500, 500, 500, 500, 500, 500, 500, 500, 500,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50])